name = "TestPluto"
uuid = "2a55602d-8229-4e79-8f04-d6411579e067"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"

[compat]
PlutoUI = "0.7"

[targets]
test = ["Test", "Jive", "PlutoUI"]
